package bwsi.registration.townhall;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class globalvar {
private static globalvar mostCurrent = new globalvar();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public static anywheresoftware.b4a.objects.CSBuilder _cstitle = null;
public static anywheresoftware.b4a.objects.CSBuilder _cssubtitle = null;
public static adr.stringfunctions.stringfunctions _sf = null;
public static String _adminpassword = "";
public static String _warningicon = "";
public static double _pricolor = 0;
public static double _seccolor = 0;
public static int _areaid = 0;
public static String _areaname = "";
public static String _areacode = "";
public static String _areadesc = "";
public static int _totreg = 0;
public static int _totunreg = 0;
public static int _totemployees = 0;
public static String _assignedemp = "";
public static String _newregno = "";
public static int _newregid = 0;
public static double _poscolor = 0;
public static double _negcolor = 0;
public static double _neutralcolor = 0;
public static anywheresoftware.b4a.keywords.constants.TypefaceWrapper _font = null;
public static anywheresoftware.b4a.keywords.constants.TypefaceWrapper _fontbold = null;
public bwsi.registration.townhall.main _main = null;
public bwsi.registration.townhall.actregistration _actregistration = null;
public bwsi.registration.townhall.registration _registration = null;
public bwsi.registration.townhall.addemployee _addemployee = null;
public bwsi.registration.townhall.dbfunctions _dbfunctions = null;
public bwsi.registration.townhall.addguest _addguest = null;
public bwsi.registration.townhall.dbutils _dbutils = null;
public bwsi.registration.townhall.mainscreen _mainscreen = null;
public bwsi.registration.townhall.scale _scale = null;
public bwsi.registration.townhall.starter _starter = null;
public bwsi.registration.townhall.httputils2service _httputils2service = null;
public bwsi.registration.townhall.b4xcollections _b4xcollections = null;
public static anywheresoftware.b4a.objects.drawable.StateListDrawable  _createbuttoncolor(anywheresoftware.b4a.BA _ba,int _focusedcolor,int _enabledcolor,int _disabledcolor,int _pressedcolor) throws Exception{
anywheresoftware.b4a.objects.drawable.StateListDrawable _retcolor = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _drwfocusedcolor = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _drwenabledcolor = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _drwdisabledcolor = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _drwpressedcolor = null;
 //BA.debugLineNum = 32;BA.debugLine="Public Sub CreateButtonColor(FocusedColor As Int,";
 //BA.debugLineNum = 34;BA.debugLine="Dim RetColor As StateListDrawable";
_retcolor = new anywheresoftware.b4a.objects.drawable.StateListDrawable();
 //BA.debugLineNum = 35;BA.debugLine="RetColor.Initialize";
_retcolor.Initialize();
 //BA.debugLineNum = 36;BA.debugLine="Dim drwFocusedColor, drwEnabledColor, drwDisabled";
_drwfocusedcolor = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
_drwenabledcolor = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
_drwdisabledcolor = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
_drwpressedcolor = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
 //BA.debugLineNum = 44;BA.debugLine="drwFocusedColor.Initialize2(FocusedColor, 25, 0,";
_drwfocusedcolor.Initialize2(_focusedcolor,(int) (25),(int) (0),anywheresoftware.b4a.keywords.Common.Colors.Black);
 //BA.debugLineNum = 45;BA.debugLine="drwEnabledColor.Initialize2(EnabledColor, 25, 0,";
_drwenabledcolor.Initialize2(_enabledcolor,(int) (25),(int) (0),anywheresoftware.b4a.keywords.Common.Colors.Black);
 //BA.debugLineNum = 46;BA.debugLine="drwDisabledColor.Initialize2(DisabledColor, 25, 2";
_drwdisabledcolor.Initialize2(_disabledcolor,(int) (25),(int) (2),anywheresoftware.b4a.keywords.Common.Colors.Black);
 //BA.debugLineNum = 47;BA.debugLine="drwPressedColor.Initialize2(PressedColor, 25, 0,";
_drwpressedcolor.Initialize2(_pressedcolor,(int) (25),(int) (0),anywheresoftware.b4a.keywords.Common.Colors.Black);
 //BA.debugLineNum = 49;BA.debugLine="RetColor.AddState(RetColor.State_Focused, drwFocu";
_retcolor.AddState(_retcolor.State_Focused,(android.graphics.drawable.Drawable)(_drwfocusedcolor.getObject()));
 //BA.debugLineNum = 50;BA.debugLine="RetColor.AddState(RetColor.State_Pressed, drwPres";
_retcolor.AddState(_retcolor.State_Pressed,(android.graphics.drawable.Drawable)(_drwpressedcolor.getObject()));
 //BA.debugLineNum = 51;BA.debugLine="RetColor.AddState(RetColor.State_Enabled, drwEnab";
_retcolor.AddState(_retcolor.State_Enabled,(android.graphics.drawable.Drawable)(_drwenabledcolor.getObject()));
 //BA.debugLineNum = 52;BA.debugLine="RetColor.AddState(RetColor.State_Disabled, drwDis";
_retcolor.AddState(_retcolor.State_Disabled,(android.graphics.drawable.Drawable)(_drwdisabledcolor.getObject()));
 //BA.debugLineNum = 53;BA.debugLine="RetColor.AddCatchAllState(drwFocusedColor)";
_retcolor.AddCatchAllState((android.graphics.drawable.Drawable)(_drwfocusedcolor.getObject()));
 //BA.debugLineNum = 54;BA.debugLine="RetColor.AddCatchAllState(drwEnabledColor)";
_retcolor.AddCatchAllState((android.graphics.drawable.Drawable)(_drwenabledcolor.getObject()));
 //BA.debugLineNum = 55;BA.debugLine="RetColor.AddCatchAllState(drwDisabledColor)";
_retcolor.AddCatchAllState((android.graphics.drawable.Drawable)(_drwdisabledcolor.getObject()));
 //BA.debugLineNum = 56;BA.debugLine="RetColor.AddCatchAllState(drwPressedColor)";
_retcolor.AddCatchAllState((android.graphics.drawable.Drawable)(_drwpressedcolor.getObject()));
 //BA.debugLineNum = 57;BA.debugLine="Return RetColor";
if (true) return _retcolor;
 //BA.debugLineNum = 59;BA.debugLine="End Sub";
return null;
}
public static anywheresoftware.b4a.objects.drawable.ColorDrawable  _mycd(anywheresoftware.b4a.BA _ba) throws Exception{
anywheresoftware.b4a.objects.drawable.ColorDrawable _mcd = null;
 //BA.debugLineNum = 61;BA.debugLine="Public Sub myCD As ColorDrawable";
 //BA.debugLineNum = 62;BA.debugLine="Dim mCD As ColorDrawable";
_mcd = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
 //BA.debugLineNum = 63;BA.debugLine="mCD.Initialize(Colors.RGB(240,240,240),0)";
_mcd.Initialize(anywheresoftware.b4a.keywords.Common.Colors.RGB((int) (240),(int) (240),(int) (240)),(int) (0));
 //BA.debugLineNum = 64;BA.debugLine="Return mCD";
if (true) return _mcd;
 //BA.debugLineNum = 65;BA.debugLine="End Sub";
return null;
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 1;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 2;BA.debugLine="Public CSTitle As CSBuilder";
_cstitle = new anywheresoftware.b4a.objects.CSBuilder();
 //BA.debugLineNum = 3;BA.debugLine="Public CSSubTitle As CSBuilder";
_cssubtitle = new anywheresoftware.b4a.objects.CSBuilder();
 //BA.debugLineNum = 5;BA.debugLine="Public SF As StringFunctions";
_sf = new adr.stringfunctions.stringfunctions();
 //BA.debugLineNum = 6;BA.debugLine="Public AdminPassword As String = \"3923bwsi12\"";
_adminpassword = "3923bwsi12";
 //BA.debugLineNum = 8;BA.debugLine="Public WarningIcon = $\"ic_warning_black_36dp2\"$ A";
_warningicon = ("ic_warning_black_36dp2");
 //BA.debugLineNum = 9;BA.debugLine="Public PriColor = 0xFF1E4369 As Double";
_pricolor = 0xff1e4369;
 //BA.debugLineNum = 10;BA.debugLine="Public SecColor = 0xFF1976D2 As Double";
_seccolor = 0xff1976d2;
 //BA.debugLineNum = 12;BA.debugLine="Public AreaID As Int";
_areaid = 0;
 //BA.debugLineNum = 13;BA.debugLine="Public AreaName As String";
_areaname = "";
 //BA.debugLineNum = 14;BA.debugLine="Public AreaCode As String";
_areacode = "";
 //BA.debugLineNum = 15;BA.debugLine="Public AreaDesc As String";
_areadesc = "";
 //BA.debugLineNum = 16;BA.debugLine="Public TotReg As Int";
_totreg = 0;
 //BA.debugLineNum = 17;BA.debugLine="Public TotUnreg As Int";
_totunreg = 0;
 //BA.debugLineNum = 18;BA.debugLine="Public TotEmployees As Int";
_totemployees = 0;
 //BA.debugLineNum = 19;BA.debugLine="Public AssignedEmp As String";
_assignedemp = "";
 //BA.debugLineNum = 21;BA.debugLine="Public NewRegNo As String";
_newregno = "";
 //BA.debugLineNum = 22;BA.debugLine="Public NewRegID As Int";
_newregid = 0;
 //BA.debugLineNum = 24;BA.debugLine="Public PosColor = 0xFF007BFF As Double";
_poscolor = 0xff007bff;
 //BA.debugLineNum = 25;BA.debugLine="Public NegColor = 0xFFDC3545 As Double";
_negcolor = 0xffdc3545;
 //BA.debugLineNum = 26;BA.debugLine="Public NeutralColor = 0xFF7FBDFF As Double";
_neutralcolor = 0xff7fbdff;
 //BA.debugLineNum = 28;BA.debugLine="Public Font As Typeface = Typeface.LoadFromAssets";
_font = new anywheresoftware.b4a.keywords.constants.TypefaceWrapper();
_font = (anywheresoftware.b4a.keywords.constants.TypefaceWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.keywords.constants.TypefaceWrapper(), (android.graphics.Typeface)(anywheresoftware.b4a.keywords.Common.Typeface.LoadFromAssets("myfont.ttf")));
 //BA.debugLineNum = 29;BA.debugLine="Public FontBold As Typeface = Typeface.LoadFromAs";
_fontbold = new anywheresoftware.b4a.keywords.constants.TypefaceWrapper();
_fontbold = (anywheresoftware.b4a.keywords.constants.TypefaceWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.keywords.constants.TypefaceWrapper(), (android.graphics.Typeface)(anywheresoftware.b4a.keywords.Common.Typeface.LoadFromAssets("myfont_bold.ttf")));
 //BA.debugLineNum = 30;BA.debugLine="End Sub";
return "";
}
}
